name: hirelyticsinc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  intl: ^0.20.1

  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # navigation
  go_router: ^14.6.3

  # fonts
  google_fonts: ^6.2.1

  # networking
  dio: ^5.7.0
  url_launcher: ^6.3.1

  # model validation
  equatable: ^2.0.7
  fpdart: ^1.1.1


  # file system management
  path_provider: ^2.1.5
  path: ^1.9.0

  # dependency injection
  get_it: ^8.0.3

  # images management
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1

  # logging
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0

  # ui
  gap: ^3.0.1
  countup: ^0.1.4

  # permission handler
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1

  # scrollable_positioned_list
  scrollable_positioned_list: ^0.3.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

  # generators
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/temp/icon_1024x1024x512.png"
  adaptive_icon_foreground: "assets/temp/icon_1024x1024x600_transparent.png"
  adaptive_icon_background: "assets/temp/icon_background_1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/temp/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
